version: '1'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
     - .:/code
     environment:
    - http_proxy=proxyapp.agea.com.ar:8080
    - https_proxy=proxyapp.agea.com.ar:8080
    - no_proxy="localhost,127.0.0.1"